### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by krau5** [utilForever/cpp-developer-roadmap#5]
I don't see anything that I have to learn if I wanna become cpp developer.
Updates?

**Comment by utilForever** [comment]
Hello, @Krausso.
First, I'm so sorry because of no updates.
I'm very busy now by implementing some open source projects such as [RosettaStone](https://github.com/utilForever/RosettaStone) and [CubbyFlow](https://github.com/utilForever/CubbyFlow).
However, I'm preparing cpp-developer-roadmap and renewal of game-developer-roadmap by year´s end.
So, please wait. 🙏

**Comment by krau5** [comment]
Okay, no problem. I was just a little bit dissapointed with last commit's date.
We are still waiting for u. GL:D

**Comment by 101Room** [comment]
May be u need help?
